Code Book: Getting and Cleaning Data - Course Project
==========================================

## Raw dataset information
This following dataset [Human Activity Recognition Using Smartphones Dataset](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones) was used to prepare tidy data that can be used for later analysis. 
#Features in the raw dataset
The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals timeAccelerometer-XYZ and timeGyroscope-XYZ. These time domain signals were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (timeBodyAccelerometer-XYZ and timeGravityAccelerometer-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 
Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (timeBodyAccelerometerJerk-XYZ and timeBodyGyroscopeJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (timeBodyAccelerometerMagnitude, timeGravityAccelerometerMagnitude, timeBodyAccelerometerJerkMagnitude, timeBodyGyroscopeMagnitude, timeBodyGyroscopeJerkMagnitude). 
Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing frequencyBodyAccelerometer-XYZ, frequencyBodyAccelerometerJerk-XYZ, frequencyBodyGyroscope-XYZ, frequencyBodyAccelerometerJerkMagnitude, frequencyBodyGyroscopeMagnitude, frequencyBodyGyroscopeJerkMagnitude.
These signals were used to estimate variables of the feature vector for each pattern: '-XYZ' is used to denote 3-axial signals in the X, Y and Z directions. 

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:

gravityMean
timeBodyAccelerometerMean
timeBodyAccelerometerJerkMean
timeBodyGyroscopeMean
timeBodyGyroscopeJerkMean

For each record it is provided:
-------------------------------------

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.


## Transformations on the raw data
The script `run_analysis.R` performs a series of steps as outlined in the course project page to transform the raw dataset in to a tidy, independent dataset. The steps perfomed are as follows:
* The test and the train datasets were combined using the `rbind()` function. 
* Only those features were selected from the raw dataset which contain measurements about either mean or standard deviation of quantities. 
* The 6 different kinds of activities were given descriptive names.
* The variable names were modified such that they are descriptive. 
* The `ddply()` function form the `plyr` package was used to group the subsetted data by each activity and each subject, and then take the average of each of the variables using the `colMeans()` function. 
* The tidy dataset, which conforms to the tidy data principles taught in Week 1 of the course, was stored in the file `tidy_data_set.txt`.


## Variables in the tidy data set 
The following 88 columns are there in the tidy data set called `tidy_data_set.txt`: 
* activity
* subject_identifier
* timeBodyAccelerometer-mean()-X
* timeBodyAccelerometer-mean()-Y
* timeBodyAccelerometer-mean()-Z
* timeBodyAccelerometer-standard_deviation()-X
* timeBodyAccelerometer-standard_deviation()-Y
* timeBodyAccelerometer-standard_deviation()-Z
* timeGravityAccelerometer-mean()-X
* timeGravityAccelerometer-mean()-Y
* timeGravityAccelerometer-mean()-Z
* timeGravityAccelerometer-standard_deviation()-X
* timeGravityAccelerometer-standard_deviation()-Y
* timeGravityAccelerometer-standard_deviation()-Z
* timeBodyAccelerometerJerk-mean()-X
* timeBodyAccelerometerJerk-mean()-Y
* timeBodyAccelerometerJerk-mean()-Z
* timeBodyAccelerometerJerk-standard_deviation()-X
* timeBodyAccelerometerJerk-standard_deviation()-Y
* timeBodyAccelerometerJerk-standard_deviation()-Z
* timeBodyGyroscope-mean()-X
* timeBodyGyroscope-mean()-Y
* timeBodyGyroscope-mean()-Z
* timeBodyGyroscope-standard_deviation()-X
* timeBodyGyroscope-standard_deviation()-Y
* timeBodyGyroscope-standard_deviation()-Z
* timeBodyGyroscopeJerk-mean()-X
* timeBodyGyroscopeJerk-mean()-Y
* timeBodyGyroscopeJerk-mean()-Z
* timeBodyGyroscopeJerk-standard_deviation()-X
* timeBodyGyroscopeJerk-standard_deviation()-Y
* timeBodyGyroscopeJerk-standard_deviation()-Z
* timeBodyAccelerometerMagnitude-mean()
* timeBodyAccelerometerMagnitude-standard_deviation()
* timeGravityAccelerometerMagnitude-mean()
* timeGravityAccelerometerMagnitude-standard_deviation()
* timeBodyAccelerometerJerkMagnitude-mean()
* timeBodyAccelerometerJerkMagnitude-standard_deviation()
* timeBodyGyroscopeMagnitude-mean()
* timeBodyGyroscopeMagnitude-standard_deviation()
* timeBodyGyroscopeJerkMagnitude-mean()
* timeBodyGyroscopeJerkMagnitude-standard_deviation()
* frequencyBodyAccelerometer-mean()-X
* frequencyBodyAccelerometer-mean()-Y
* frequencyBodyAccelerometer-mean()-Z
* frequencyBodyAccelerometer-standard_deviation()-X
* frequencyBodyAccelerometer-standard_deviation()-Y
* frequencyBodyAccelerometer-standard_deviation()-Z
* frequencyBodyAccelerometer-meanFreq()-X
* frequencyBodyAccelerometer-meanFreq()-Y
* frequencyBodyAccelerometer-meanFreq()-Z
* frequencyBodyAccelerometerJerk-mean()-X
* frequencyBodyAccelerometerJerk-mean()-Y
* frequencyBodyAccelerometerJerk-mean()-Z
* frequencyBodyAccelerometerJerk-standard_deviation()-X
* frequencyBodyAccelerometerJerk-standard_deviation()-Y
* frequencyBodyAccelerometerJerk-standard_deviation()-Z
* frequencyBodyAccelerometerJerk-meanFreq()-X
* frequencyBodyAccelerometerJerk-meanFreq()-Y
* frequencyBodyAccelerometerJerk-meanFreq()-Z
* frequencyBodyGyroscope-mean()-X
* frequencyBodyGyroscope-mean()-Y
* frequencyBodyGyroscope-mean()-Z
* frequencyBodyGyroscope-standard_deviation()-X
* frequencyBodyGyroscope-standard_deviation()-Y
* frequencyBodyGyroscope-standard_deviation()-Z
* frequencyBodyGyroscope-meanFreq()-X
* frequencyBodyGyroscope-meanFreq()-Y
* frequencyBodyGyroscope-meanFreq()-Z
* frequencyBodyAccelerometerMagnitude-mean()
* frequencyBodyAccelerometerMagnitude-standard_deviation()
* frequencyBodyAccelerometerMagnitude-meanFreq()
* frequencyBodyBodyAccelerometerJerkMagnitude-mean()
* frequencyBodyBodyAccelerometerJerkMagnitude-standard_deviation()
* frequencyBodyBodyAccelerometerJerkMagnitude-meanFreq()
* frequencyBodyBodyGyroscopeMagnitude-mean()
* frequencyBodyBodyGyroscopeMagnitude-standard_deviation()
* frequencyBodyBodyGyroscopeMagnitude-meanFreq()
* frequencyBodyBodyGyroscopeJerkMagnitude-mean()
* frequencyBodyBodyGyroscopeJerkMagnitude-standard_deviation()
* frequencyBodyBodyGyroscopeJerkMagnitude-meanFreq()
* angle(timeBodyAccelerometerMean,gravity)
* angle(timeBodyAccelerometerJerkMean),gravityMean)
* angle(timeBodyGyroscopeMean,gravityMean)
* angle(timeBodyGyroscopeJerkMean,gravityMean)
* angle(X,gravityMean)
* angle(Y,gravityMean)
* angle(Z,gravityMean)



